### ISSUE TITLE
[WINDOWS10/CPU] Progress hangs at 0%

### ISSUE THREAD

**Issue by s20290** [Stability-AI/stablediffusion#183]
For extra information, in case the problem lies elsewhere, I am using windows10, python3.9. Can't install intel extention for pytorch cuz it tells me 
```
ERROR: Could not find a version that satisfies the requirement intel_extension_for_pytorch==1.13.1 (from versions: none)
ERROR: No matching distribution found for intel_extension_for_pytorch==1.13.1
```
but as far as I understand it is only for optimization anyways.

The script just hangs at the watermark stage, or at least I assume it is hanging. Any clues?

```
PS D:\codes\stableDiffuse\stablediffusion> python39 .\scripts\txt2img.py --H '200' --W '200' --prompt 'cool looking cat' --outdir D:\codes\stableDiffuse\stableDiff_1\coolcat --ckpt '.\768-v-ema.ckpt' --steps '10' --config .\configs\stable-diffusion\intel\v2-inference-bf16.yaml
Global seed set to 42
Loading model from .\768-v-ema.ckpt
Global Step: 140000
No module 'xformers'. Proceeding without it.
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 865.91 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Creating invisible watermark encoder (see https://github.com/ShieldMnt/invisible-watermark)...
Sampling:   0%|                                                                                                       | 0/3 [00:00<?, ?it/s]
data:   0%|                                                                                                           | 0/1 [00:00<?, ?it/s]
```

**Comment by francescapalermo** [comment]
I thought the same when first running it! But the code is running and training the attention heads even if not updating the tqdm. 
You can debug it by adding a printing line in `def text_transformer_forward` in the `modules.py` script.

After that, the model will continue training but I always get stuck with the following error: `RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'`. I think this version is not working with Windows because of the xconders library not recognising the GPU. 
You can try installing the [User Interface](https://github.com/cmdr2/stable-diffusion-ui) version instead which works perfectly on Windows
