### ISSUE TITLE
[WINDOWS10/CPU/CUDA] float type issues

### ISSUE THREAD

**Issue by s20290** [Stability-AI/stablediffusion#186]
I have been trying to generate just one image but keep getting issues related to float. I am executing the following command.

```
python39 ./scripts/txt2img.py --prompt "a professional photograph of an astronaut riding a horse" --ckpt .\768-v-ema.ckpt --config  .\configs\stable-diffusion\v2-inference-v.yaml --H 200 --W 200 
```
or this (cuda)
```
python39 ./scripts/txt2img.py --prompt "a professional photograph of an astronaut riding a horse" --ckpt .\768-v-ema.ckpt --config  .\configs\stable-diffusion\v2-inference-v.yaml --H 200 --W 200  --precision full --device cuda
```

I get this error.
```
RuntimeError: expected scalar type BFloat16 but found Float
```

I have read that "--precision full" may help so I tried it but I get this.

```
RuntimeError: Input type (struct c10::Half) and bias type (float) should be the same
```

It is quite weird because UI version works, and I just wonder why. Is it running on some kind of container? Why am I getting these errors? Am I using the wrong commands?

**Comment by s20290** [comment]
i added "--bf16" to the command but now i am getting out of memory error. Solved but not done with my journey yet.

**Comment by guijuzhejiang** [comment]
try to add --device cuda

**Comment by kaykyr** [comment]
> --device cuda

Hello! Ive tried it but I got this:

NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs:
     query       : shape=(30, 9216, 1, 64) (torch.float16)
     key         : shape=(30, 9216, 1, 64) (torch.float16)
     value       : shape=(30, 9216, 1, 64) (torch.float16)
     attn_bias   : <class 'NoneType'>
     p           : 0.0
`cutlassF` is not supported because:
    xFormers wasn't build with CUDA support
`flshattF` is not supported because:
    xFormers wasn't build with CUDA support
`tritonflashattF` is not supported because:
    xFormers wasn't build with CUDA support
    triton is not available
    requires A100 GPU
`smallkF` is not supported because:
    xFormers wasn't build with CUDA support
    dtype=torch.float16 (supported: {torch.float32})
    max(query.shape[-1] != value.shape[-1]) > 32
    unsupported embed per head: 64

**Comment by MachineGunLin** [comment]
> > --device cuda
> 
> Hello! Ive tried it but I got this:
> 
> NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs: query : shape=(30, 9216, 1, 64) (torch.float16) key : shape=(30, 9216, 1, 64) (torch.float16) value : shape=(30, 9216, 1, 64) (torch.float16) attn_bias : <class 'NoneType'> p : 0.0 `cutlassF` is not supported because: xFormers wasn't build with CUDA support `flshattF` is not supported because: xFormers wasn't build with CUDA support `tritonflashattF` is not supported because: xFormers wasn't build with CUDA support triton is not available requires A100 GPU `smallkF` is not supported because: xFormers wasn't build with CUDA support dtype=torch.float16 (supported: {torch.float32}) max(query.shape[-1] != value.shape[-1]) > 32 unsupported embed per head: 64

Have you solved this problem?

**Comment by ren-echo** [comment]
> > --device cuda
> 
> Hello! Ive tried it but I got this:
> 
> NotImplementedError: No operator found for with inputs: query : shape=(30, 9216, 1, 64) (torch.float16) key : shape=(30, 9216, 1, 64) (torch.float16) value : shape=(30, 9216, 1, 64) (torch.float16) attn_bias : <class 'NoneType'> p : 0.0 is not supported because: xFormers wasn't build with CUDA support is not supported because: xFormers wasn't build with CUDA support is not supported because: xFormers wasn't build with CUDA support triton is not available requires A100 GPU is not supported because: xFormers wasn't build with CUDA support dtype=torch.float16 (supported: {torch.float32}) max(query.shape[-1] != value.shape[-1]) > 32 unsupported embed per head: 64`memory_efficient_attention_forward``cutlassF``flshattF``tritonflashattF``smallkF`

My problem is the same as yours. Has it been solved?

**Comment by ren-echo** [comment]
I received the following error message.
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.4.0+cu121 with CUDA 1201 (you have 2.4.0+cpu)
    Python  3.12.4 (you have 3.12.2)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
D:\Depth-Anything\run.py:42: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  depth_anything.load_state_dict(torch.load('./checkpoint/depth_anything_vitl14/pytorch_model.bin'))
Total parameters: 335.32M
  0%|          | 0/19 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "D:\Depth-Anything\run.py", line 87, in <module>
    depth = depth_anything(image)
            ^^^^^^^^^^^^^^^^^^^^^
  File "E:\ANACONDA\envs\p111\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ANACONDA\envs\p111\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Depth-Anything\depth_anything\dpt.py", line 158, in forward
    features = self.pretrained.get_intermediate_layers(x, 4, return_class_token=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Depth-Anything\torchhub/facebookresearch_dinov2_main\vision_transformer.py", line 308, in get_intermediate_layers
    outputs = self._get_intermediate_layers_not_chunked(x, n)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Depth-Anything\torchhub/facebookresearch_dinov2_main\vision_transformer.py", line 277, in _get_intermediate_layers_not_chunked
    x = blk(x)
        ^^^^^^
  File "E:\ANACONDA\envs\p111\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ANACONDA\envs\p111\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Depth-Anything\torchhub/facebookresearch_dinov2_main\dinov2\layers\block.py", line 247, in forward
    return super().forward(x_or_x_list)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Depth-Anything\torchhub/facebookresearch_dinov2_main\dinov2\layers\block.py", line 105, in forward
    x = x + attn_residual_func(x)
            ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Depth-Anything\torchhub/facebookresearch_dinov2_main\dinov2\layers\block.py", line 84, in attn_residual_func
    return self.ls1(self.attn(self.norm1(x)))
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ANACONDA\envs\p111\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ANACONDA\envs\p111\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Depth-Anything\torchhub/facebookresearch_dinov2_main\dinov2\layers\attention.py", line 76, in forward
    x = memory_efficient_attention(q, k, v, attn_bias=attn_bias)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ANACONDA\envs\p111\Lib\site-packages\xformers\ops\fmha\__init__.py", line 276, in memory_efficient_attention
    return _memory_efficient_attention(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ANACONDA\envs\p111\Lib\site-packages\xformers\ops\fmha\__init__.py", line 395, in _memory_efficient_attention
    return _memory_efficient_attention_forward(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ANACONDA\envs\p111\Lib\site-packages\xformers\ops\fmha\__init__.py", line 414, in _memory_efficient_attention_forward
    op = _dispatch_fw(inp, False)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ANACONDA\envs\p111\Lib\site-packages\xformers\ops\fmha\dispatch.py", line 119, in _dispatch_fw
    return _run_priority_list(
           ^^^^^^^^^^^^^^^^^^^
  File "E:\ANACONDA\envs\p111\Lib\site-packages\xformers\ops\fmha\dispatch.py", line 55, in _run_priority_list
    raise NotImplementedError(msg)
NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs:
     query       : shape=(1, 2073, 16, 64) (torch.float32)
     key         : shape=(1, 2073, 16, 64) (torch.float32)
     value       : shape=(1, 2073, 16, 64) (torch.float32)
     attn_bias   : <class 'NoneType'>
     p           : 0.0
`ckF` is not supported because:
    device=cpu (supported: {'cuda'})
    dtype=torch.float32 (supported: {torch.float16, torch.bfloat16})
    operator wasn't built - see `python -m xformers.info` for more info
